export const projects = [
  {
    name: "Wecome Events",
    description: "bla bla",
    technologies: " bla bla",
    image: "image link or only name",
    github: "github link if exist",
    demo: "demi link if exist",
    video: "video link if exist",
  },
  {
    name: "Tipper",
    description: "bla bla",
    technologies: " bla bla",
    image: "image link or only name",
    github: "github link if exist",
    demo: "demi link if exist",
    video: "video link if exist",
  },
  {
    name: "Spot and Share",
    description: "bla bla",
    technologies: " bla bla",
    image: "image link or only name",
    github: "github link if exist",
    demo: "demi link if exist",
    video: "video link if exist",
  },
  {
    name: "Portfolio",
    description: "bla bla",
    technologies: " bla bla",
    image: "image link or only name",
    github: "github link if exist",
    demo: "demi link if exist",
    video: "video link if exist",
  },
  {
    name: "Landing Page Generator",
    description: "bla bla",
    technologies: " bla bla",
    image: "image link or only name",
    github: "github link if exist",
    demo: "demi link if exist",
    video: "video link if exist",
  },
  {
    name: "Corona Statistics",
    description: "bla bla",
    technologies: " bla bla",
    image: "image link or only name",
    github: "github link if exist",
    demo: "demi link if exist",
    video: "video link if exist",
  },
  {
    name: "Dice Game",
    description: "bla bla",
    technologies: " bla bla",
    image: "image link or only name",
    github: "github link if exist",
    demo: "demi link if exist",
    video: "video link if exist",
  },
];
